# Generated by Django 3.2.10 on 2022-03-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategories',
            name='base64',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
