# Generated by Django 3.2.10 on 2023-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0002_alter_projectcategories_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategories',
            name='base64',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='ph_c_date',
            field=models.DateTimeField(auto_now_add=True, max_length=250, verbose_name='ph_c_date'),
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='ph_m_date',
            field=models.DateTimeField(auto_now_add=True, max_length=250, verbose_name='ph_m_date'),
        ),
    ]
