# Generated by Django 3.2.10 on 2023-02-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0003_auto_20230203_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_subscribers', models.CharField(blank=True, max_length=250, null=True)),
                ('amt_per_user', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
