# Generated by Django 3.2.10 on 2023-02-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
