# Generated by Django 3.2.10 on 2023-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0005_subscriptionplan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='center',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geocountriescurrencies',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geocountriescurrencies',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geotimezones',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geotimezones',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geozones',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='geozones',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='masterleavetypes',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='masterleavetypes',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='people',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='people',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='prefixsuffix',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='prefixsuffix',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='days_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='reg_users',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='tag',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='taskprojectcategorieschecklist',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='taskprojectcategorieschecklist',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='usersleaveapplications',
            name='c_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
        migrations.AddField(
            model_name='usersleaveapplications',
            name='m_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp'),
        ),
    ]
